export const SET_TOKEN = "SET_TOKEN";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const SET_QUESTIONS = "SET_QUESTIONS";

export const SET_RANKS = "SET_RANKS";

export const FILTER_RANKS_CLASS = "FILTER_RANKS_CLASS";

export const SET_USER = "SET_USER";

export const UPDATE_RANKS_SUCCESS = "UPDATE_RANKS_SUCCESS";

export const UPLOAD_RANKS_SUCCESS = "UPLOAD_RANKS_SUCCESS";

export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";

export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
